org: stoerk
app: sillium-apis
service: flask-tv-api

frameworkVersion: '2'

custom:
  basePath:
    dev: dev
    prod: ''
  wsgi:
    app: app.app
  customDomain:
    domainName: tagesthemen.sillium.org
    certificateName: 'tagesthemen.sillium.org'
    basePath: ${self:custom.basepath.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true
  customCertificate:
    certificateName: 'tagesthemen.sillium.org'
    hostedZoneNames: 'sillium.org.'
    region: eu-east-1
    rewriteRecords: false
  scripts:
    hooks:
      'before:deploy:deploy': serverless create-cert; serverless create_domain --stage ${self:provider.stage} --verbose

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  memorySize: 128
  timeout: 5
  tracing:
    lambda: true

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-plugin-scripts
  - serverless-domain-manager
  - serverless-certificate-creator

