org: stoerk
app: sillium-apis
service: flask-tv-api

frameworkVersion: '2'

custom:
  basePath:
    dev: dev
    prod: ''
  wsgi:
    app: app.app
  customDomain:
    domainName: tagesthemen.api.sillium.xyz
    certificateName: '*.api.sillium.xyz'
    hostedZoneId: Z04645421K92MX0ACC0PF
    basePath: ${self:custom.basepath.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true
  scripts:
    hooks:
      'before:deploy:deploy': serverless create_domain --stage ${self:provider.stage} --verbose

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  memorySize: 128
  timeout: 5
  tracing:
    lambda: true

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-plugin-scripts
