org: stoerk
app: sillium-apis
service: flask-tv-api

frameworkVersion: '2'

custom:
  stage: ${opt:stage}
  domainName:
    dev: tagesthemen.dev.sillium.org
    prod: tagesthemen.sillium.org
  wsgi:
    app: app.app
  customDomain:
    domainName: ${self:custom.domainName.${self:custom.stage}}
#    certificateName: '*.sillium.org'
    basePath: ''
    hostedZoneId: ${param:hostedZoneId}
    createRoute53Record: true
    autoDomain: true
    certificateArn: ${param:certificateArn}
  scripts:
    hooks:
      'before:deploy:deploy': export SLS_DEBUG=*; serverless create_domain --stage ${self:custom.stage};

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}
  lambdaHashingVersion: '20201221'
  memorySize: 128
  timeout: 5
  tracing:
    lambda: true

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-plugin-scripts
  - serverless-domain-manager
