org: stoerk
app: sillium-apis
service: flask-tv-api

frameworkVersion: '2'

custom:
  stage: ${opt:stage}
  basePath:
    dev: dev
    prod: prod
  wsgi:
    app: app.app
  customDomain:
    domainName: tagesthemen.sillium.org
    certificateName: 'tagesthemen.sillium.org'
    basePath: ${self:custom.basePath.${self:custom.stage}}
    stage: ${self:custom.stage}
    createRoute53Record: true
    autoDomain: true
  customCertificate:
    certificateName: 'tagesthemen.sillium.org'
    hostedZoneNames: 'sillium.org.'
    region: us-east-1
    rewriteRecords: false
  scripts:
    hooks:
      'before:deploy:deploy': serverless create-cert --stage ${self:custom.stage}; serverless delete_domain --stage ${self:custom.stage}; serverless create_domain --stage ${self:custom.stage} --verbose

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}
  lambdaHashingVersion: '20201221'
  memorySize: 128
  timeout: 5
  tracing:
    lambda: true

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-plugin-scripts
  - serverless-domain-manager
  - serverless-certificate-creator

