org: stoerk
app: sillium-tagesthemen
service: tagesthemen

frameworkVersion: '2'

custom:
  stage: ${opt:stage}
  dev: 
    domainName: dev.${self:service}.sillium.xyz
  prod:
    domainName: ${self:service}.sillium.xyz
  wsgi:
    app: app.app
  apiCloudFront:
    domain: ${self:custom.${self:custom.stage}.domainName}
    certificate: ${param:certificateArn}
    logging:
      bucket: ${self:app}-${self:custom.stage}-cloudfront-logs.s3.amazonaws.com
      prefix: ${self:service}/${self:custom.stage}
    cookies: none
  pythonRequirements:
    pythonBin: python3

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}
  lambdaHashingVersion: '20201221'
  logRetentionInDays: 7
  memorySize: 128
  timeout: 15
  region: eu-central-1
  deploymentBucket:
      name: ${self:app}-${self:custom.stage}-serverless-deployments
  tracing:
    lambda: true
  stackTags:
    source: https://github.com/Sillium/tagesthemen
    serverlessOrg: ${self:org}
    serverlessApp: ${self:app}
    serverlessService: ${self:service}
    serverlessStage: ${self:custom.stage}

functions:
  getStartTime:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: GET

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-api-cloudfront
  - serverless-deployment-bucket
  - serverless-s3-remover

resources:
  Resources:
    CloudFrontLogsS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:app}-${self:custom.stage}-cloudfront-logs
        AccessControl: BucketOwnerFullControl
        VersioningConfiguration:
          Status: Enabled