org: stoerk
app: sillium-apis
service: tagesthemen

frameworkVersion: '2'

custom:
  stage: ${opt:stage}
  dev: 
    domainName: ${self:service}.dev.sillium.org
  prod:
    domainName: ${self:service}.sillium.org
  wsgi:
    app: app.app
  apiCloudFront:
    domain: ${self:custom.${self:custom.stage}.domainName}
    certificate: ${param:certificateArn}
    logging:
      bucket: sillium-apis-cloudfront-logs.s3.amazonaws.com
      prefix: ${self:service}
    cookies: none
  pythonRequirements:
    pythonBin: python3

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}
  lambdaHashingVersion: '20201221'
  logRetentionInDays: 7
  memorySize: 128
  timeout: 15
  region: eu-central-1
  deploymentBucket: sillium-apis-serverless-deployments
  tracing:
    lambda: true
  stackTags:
    source: https://github.com/Sillium/tagesthemen
    serverlessOrg: ${self:org}
    serverlessApp: ${self:app}
    serverlessService: ${self:service}
    serverlessStage: ${self:custom.stage}

functions:
  getStartTime:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: GET

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-api-cloudfront
